package:
  name: scippbuildtools
  version: 0.0.1

source:
  path: ..

requirements:
  build:
    - setuptools

test:
  imports:
    - scippbuildtools

build:
  number: 2
  noarch: python
  script:
    - python setup.py install

about:
  home: https://github.com/scipp/scippbuildtools
  license: BSD-3-Clause
  summary: Tools for building C++ libraries, python packages and documentation
  description: Tools for building C++ libraries, python packages and documentation
  dev_url: https://github.com/scipp/scippbuildtools
  doc_url:
